services:
  db:
    image: postgres:alpine
    ports:
      - 6543:5432
    environment:
      POSTGRES_PASSWORD: ${DbPassword}
      POSTGRES_USERNAME: liquibase
      POSTGRES_DB: open-cms
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s